bscitgroup/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using bscitgroup.Models;

namespace bscitgroup.Controllers
{
    public class PersonasController : Controller
    {
        private readonly bscitgroupContext _context;
         
        public PersonasController(bscitgroupContext context)
        {
            _context = context;
        }

        // GET: Personas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Persona.ToListAsync());
        }

        // GET: Personas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Persona
                .SingleOrDefaultAsync(m => m.DNI == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // GET: Personas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DNI,Nombre,Apellido,Celular,Telefono,Pais,Ciudad,Profesion,Institucion,Correo")] Persona persona)
        {
            if (ModelState.IsValid)
            {
                _context.Add(persona);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Personas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Persona.SingleOrDefaultAsync(m => m.DNI == id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DNI,Nombre,Apellido,Celular,Telefono,Pais,Ciudad,Profesion,Institucion,Correo")] Persona persona)
        {
            if (id != persona.DNI)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(persona);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonaExists(persona.DNI))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Personas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Persona
                .SingleOrDefaultAsync(m => m.DNI == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var persona = await _context.Persona.SingleOrDefaultAsync(m => m.DNI == id);
            _context.Persona.Remove(persona);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonaExists(int id)
        {
            return _context.Persona.Any(e => e.DNI == id);
        }
    }
}

bscitgroup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" , shrink-to-fit=no />
    <title>@ViewData["Title"] - Grupo BSCIT</title>

    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template
        /vendor/font-awesome/css/font-awesome.min.css
        //code.jquery.com/jquery-1.12.0.min.js
        vendor/magnific-popup/magnific-popup.css
        -->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="~/code.jquery.com/jquery-1.12.0.min.js"></script>
    <!-- Plugin CSS -->
    <link href="~/vendor/magnific-popup/magnific-popup.css" rel="stylesheet">
    <script>
        $(document).ready(function () {
            $("#mostrarmodal").modal("show");
        });
    </script>
    <link href="~/css/creative.min.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">

    <!--
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
        -->
</head>

<!-- Body -->
<body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">Grupo - BSCIT</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#about">Nosotros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#services">Servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#portfolio">Cursos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#contact">Contactenos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#contact">Registrar</a>
                    <li class="nav-item">
                        <a>
                            <form method="post" action='@Url.Action("Create", "Personas")'>
                                Registrar
                                
                            </form>
                        </a>
 


                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#contact">Entrar</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


        @RenderBody()
        <hr />
         <footer id="footer" class="footer">
            <div class="container">
                <div class="row titulos-footer">
                    <div class="col-sm-3"><picture><img src="img/portfolio/fullsize/logo.jpg" class="img-responsive" alt="BSCIT" title="BSCIT"></picture></div>
                    <div class="col-sm-3">
                        <a class="titulo">BSCIT</a>
                        <ul class="sub-menu-footer">
                            <li><a href="/acerca-bsgrupo#valores">Valores corporativos</a></li>
                            <li><a href="/acerca-bsgrupo#numeros">En números</a></li>
                            <li><a href="/acerca-bsgrupo#vision">Nuestra visión</a></li>
                            <li><a href="/acerca-bsgrupo#politica-calidad">Política de calidad</a></li>
                            <li><a href="/acerca-bsgrupo#nuestros-estudiantes">Nuestros estudiantes</a></li>
                            <li><a href="/acerca-bsgrupo#liderazgo">Liderazgo</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-3">
                        <a class="titulo">SERVICIOS</a>
                        <ul class="sub-menu-footer">
                            <li><a href="/carreras-profesionales" id="carrerasprofesionalesfooter">Carreras Profesionales</a></li>
                            <li><a href="/programas-certificaciones-cursos" id="cursosfooter">Formación Continua</a></li>
                            <li><a href="/servicios-corporativos" id="servicioscorporativos">Servicios Corporativos</a></li>
                            <li><a href="https://facturacion.bsgrupo.com/" id="facturaelectronica" target="_blank">Facturación Electrónica</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-3">
                        <a class="titulo">MÁS</a>
                        <ul class="sub-menu-footer">
                            <li><a href="/link" id="bolsatrabajo" target="_blank">Bolsa de trabajo</a></li>
                            <li><a href="#" id="correoweb">Correo Web</a></li>
                            <li><a href="/mapa-del-sitio" id="mapasitio">Mapa del Sitio</a></li>
                            <li><a href="/contactenos?returnUrl=%2F" id="contactenos">Contáctanos</a></li>
                        </ul>
                        <b class="social">SIGUENOS EN</b>
                        <div class="row fan-page">
                            <div class="espaciox1">
                                <div class="col-xs-1 facebook">
                                    <a href="https://www.facebook.com/BS.Grupo.Oficial" target="_blank" id="redsocialfacebook"><i class="icon-facebook"></i></a>
                                </div>
                                <div class="col-xs-1"></div>
                                <div class="col-xs-1 twitter">
                                    <a href="https://twitter.com/BS_Grupo" target="_blank" id="redsocialtwitter"><i class="icon-twitter"></i></a>
                                </div>
                                <div class="col-xs-1"></div>
                                <div class="col-xs-1 youtube">
                                    <a href="https://www.youtube.com/user/BSGRUPOsac" target="_blank" id="redesocialyoutube"><i class="icon-youtube"></i></a>
                                </div>
                                <div class="col-xs-1"></div>
                                <div class="col-xs-1 googleplus">
                                    <a href="https://plus.google.com/114741006710838906433/posts" target="_blank" id="redesocialplus"><i class="icon-google-plus"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="Derechos">
                    © 2018 BSCIT, todos los derechos reservados • <a href="/termino-uso-web" id="terminousowebfooter">Términos de uso</a> • <a href="/politica-privacidad" id="politicaprivacidadfooter">Política de privacidad</a>
                </div>
                <div class="Derechos">
                </div>
            </div>
            <p>&copy; 2018 - WebApplication2</p>
        </footer>
  

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="~/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- Custom scripts for this template -->
    <script src="~/js/creative.min.js"></script>




    @RenderSection("Scripts", required: false)


</body>
</html>